Referred to MY_fin_bloomberg_code_1.ipynb

In [803]:
import pandas as pd
import openpyxl 
from datetime import datetime 
import calendar

In [804]:
bloomberg = pd.ExcelFile("..\Sray\original dirty data\CN_ESG & fin data_bloomberg.xlsx")
# bloomberg = pd.ExcelFile("..\Sray\original dirty data\AU_ESG & fin data_bloomberg.xlsx")
# bloomberg = pd.ExcelFile("..\Sray\original dirty data\HK_ESG & fin data_bloomberg.xlsx")
# bloomberg = pd.ExcelFile("..\Sray\original dirty data\MY_ESG & fin data_bloomberg.xlsx")
# bloomberg = pd.ExcelFile("..\Sray\original dirty data\SG_ESG & fin data_bloomberg.xlsx")



names = bloomberg.sheet_names
fin_data = pd.DataFrame()

for name in names:
    if ('financial' in name.lower()):
        findata_sheet = pd.read_excel(bloomberg, sheet_name=name, header=1)
        fin_data = pd.DataFrame(findata_sheet)

fin_data.head()

,End Date,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14324,Unnamed: 14325,Unnamed: 14326,Unnamed: 14327,Unnamed: 14328,Unnamed: 14329,Unnamed: 14330,Unnamed: 14331,Unnamed: 14332,Unnamed: 14333
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,002007 CH Equity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Dates,PX_LAST,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,CF_FREE_CASH_FLOW,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,...,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,CF_FREE_CASH_FLOW,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,VOLATILITY_360D,BETA_RAW_OVERRIDABLE
3,2023-01-31 00:00:00,22.3,33130.4997,2.5659,0.1741,77.3828,35.5719,12.4809,8.8031,43.782,...,5847.9545,4.0972,0.0487,112.6397,64.4757,10.5395,1.9394,40.799,41.581,1.2659
4,2022-12-30 00:00:00,22.63,33130.4997,2.5659,0.1741,77.3828,36.0983,12.4809,8.8031,45.394,...,5847.9545,4.0972,0.0487,112.6397,60.9747,10.5395,1.9394,43.11,41.779,1.267

Get the list of the companies

In [805]:
company_list = (fin_data.iloc[1]).to_list()
company_list = [element for element in company_list if str(element) != "nan"]
print(company_list)

['002007 CH Equity', '600682 CH Equity', '600372 CH Equity', '000008 CH Equity', '002624 CH Equity', '002596 CH Equity', '600745 CH Equity', '600298 CH Equity', '600110 CH Equity', '000666 CH Equity', '600717 CH Equity', '600724 CH Equity', '000671 CH Equity', '002672 CH Equity', '000983 CH Equity', '600063 CH Equity', '002635 CH Equity', '200761 CH Equity', '600748 CH Equity', '600688 CH Equity', '000596 CH Equity', '600522 CH Equity', '600388 CH Equity', '600096 CH Equity', '600000 CH Equity', '601666 CH Equity', '600282 CH Equity', '000062 CH Equity', '600496 CH Equity', '600315 CH Equity', '300113 CH Equity', '000918 CH Equity', '600725 CH Equity', '600307 CH Equity', '000415 CH Equity', '002600 CH Equity', '002003 CH Equity', '002033 CH Equity', '600561 CH Equity', '601098 CH Equity', '000962 CH Equity', '601398 CH Equity', '600598 CH Equity', '600116 CH Equity', '600995 CH Equity', '600171 CH Equity', '600980 CH Equity', '600438 CH Equity', '600004 CH Equity', '600526 CH Equity', '600390 CH Equity', '600979 CH Equity', '600252 CH Equity', '600516 CH Equity', '600369 CH Equity', '000701 CH Equity', '000980 CH Equity', '600872 CH Equity', '601231 CH Equity', '601999 CH Equity', '600350 CH Equity', '600132 CH Equity', '601928 CH Equity', '601233 CH Equity', '300296 CH Equity', '002120 CH Equity', '600859 CH Equity', '600193 CH Equity', '002035 CH Equity', '600340 CH Equity', '601258 CH Equity', '600006 CH Equity', '600098 CH Equity', '002230 CH Equity', '300257 CH Equity', '600850 CH Equity', '600380 CH Equity', '002203 CH Equity', '000753 CH Equity', '002129 CH Equity', '600858 CH Equity', '600160 CH Equity', '600418 CH Equity', '000895 CH Equity', '000650 CH Equity', '600360 CH Equity', '600569 CH Equity', '600869 CH Equity', '000799 CH Equity', '600458 CH Equity', '000683 CH Equity', '600104 CH Equity', '600567 CH Equity', '002130 CH Equity', '000903 CH Equity', '600346 CH Equity', '000078 CH Equity', '600339 CH Equity', '000759 CH Equity', '000632 CH Equity', '600582 CH Equity', '600266 CH Equity', '600389 CH Equity', '002123 CH Equity', '600422 CH Equity', '600161 CH Equity', '600376 CH Equity', '000990 CH Equity', '000623 CH Equity', '600399 CH Equity', '600383 CH Equity', '600466 CH Equity', '000858 CH Equity', '600255 CH Equity', '002072 CH Equity', '000927 CH Equity', '600258 CH Equity', '200028 CH Equity', '002460 CH Equity', '600900 CH Equity', '600501 CH Equity', '600871 CH Equity', '600488 CH Equity', '600600 CH Equity', '002027 CH Equity', '600502 CH Equity', '600463 CH Equity', '002607 CH Equity', '601718 CH Equity', '600999 CH Equity', '600535 CH Equity', '600173 CH Equity', '600288 CH Equity', '000999 CH Equity', '600425 CH Equity', '600038 CH Equity', '600988 CH Equity', '600575 CH Equity', '600351 CH Equity', '002407 CH Equity', '600203 CH Equity', '600967 CH Equity', '300297 CH Equity', '000767 CH Equity', '600251 CH Equity', '002075 CH Equity', '600985 CH Equity', '600970 CH Equity', '600381 CH Equity', '600975 CH Equity', '000537 CH Equity', '002185 CH Equity', '000536 CH Equity', '002099 CH Equity', '000528 CH Equity', '600809 CH Equity', '000793 CH Equity', '600560 CH Equity', '000776 CH Equity', '002008 CH Equity', '200530 CH Equity', '000538 CH Equity', '000563 CH Equity', '600416 CH Equity', '600456 CH Equity', '600511 CH Equity', '600505 CH Equity', '002179 CH Equity', '002133 CH Equity', '000066 CH Equity', '600177 CH Equity', '002023 CH Equity', '600010 CH Equity', '600966 CH Equity', '600570 CH Equity', '002500 CH Equity', '900905 CH Equity', '002157 CH Equity', '600467 CH Equity', '000503 CH Equity', '002167 CH Equity', '002152 CH Equity', '600071 CH Equity', '002054 CH Equity', '000728 CH Equity', '002151 CH Equity', '002106 CH Equity', '600361 CH Equity', '300027 CH Equity', '600478 CH Equity', '002127 CH Equity', '601818 CH Equity', '002019 CH Equity', '600557 CH Equity', '601958 CH Equity', '601377 CH Equity', '600559 CH Equity', '002233 CH Equity', '002011 CH Equity', '601333 CH Equity', '000156 CH Equity', '600497 CH Equity', '600897 CH Equity', '600103 CH Equity', '600711 CH Equity', '600262 CH Equity', '000732 CH Equity', '002162 CH Equity', '600459 CH Equity', '002311 CH Equity', '002439 CH Equity', '000933 CH Equity', '600429 CH Equity', '600987 CH Equity', '601801 CH Equity', '300251 CH Equity', '600528 CH Equity', '600563 CH Equity', '002050 CH Equity', '900923 CH Equity', '600208 CH Equity', '600887 CH Equity', '002424 CH Equity', '002358 CH Equity', '600733 CH Equity', '000982 CH Equity', '300078 CH Equity', '600395 CH Equity', '900912 CH Equity', '601018 CH Equity', '600030 CH Equity', '601118 CH Equity', '600095 CH Equity', '000893 CH Equity', '600397 CH Equity', '002396 CH Equity', '002371 CH Equity', '000061 CH Equity', '002542 CH Equity', '600547 CH Equity', '601727 CH Equity', '200026 CH Equity', '600990 CH Equity', '300207 CH Equity', '002273 CH Equity', '002271 CH Equity', '601360 CH Equity', '002285 CH Equity', '600565 CH Equity', '600426 CH Equity', '600297 CH Equity', '002140 CH Equity', '300285 CH Equity', '601216 CH Equity', '002416 CH Equity', '000762 CH Equity', '002434 CH Equity', '300015 CH Equity', '002299 CH Equity', '000828 CH Equity', '300009 CH Equity', '000750 CH Equity', '300136 CH Equity', '300188 CH Equity', '300098 CH Equity', '002411 CH Equity', '601311 CH Equity', '300043 CH Equity', '002426 CH Equity', '300059 CH Equity', '000860 CH Equity', '002410 CH Equity', '300146 CH Equity', '600058 CH Equity', '002399 CH Equity', '000407 CH Equity', '000709 CH Equity', '002326 CH Equity', '600428 CH Equity', '300133 CH Equity', '601788 CH Equity', '002170 CH Equity', '002223 CH Equity', '002024 CH Equity', '600060 CH Equity', '300072 CH Equity', '002491 CH Equity', '300002 CH Equity', '300253 CH Equity', '002280 CH Equity', '002431 CH Equity', '002344 CH Equity', '002128 CH Equity', '002568 CH Equity', '002489 CH Equity', '002049 CH Equity', '001914 CH Equity', '002444 CH Equity', '300058 CH Equity', '600834 CH Equity', '000712 CH Equity', '600824 CH Equity', '600863 CH Equity', '601933 CH Equity', '002314 CH Equity', '002056 CH Equity', '300033 CH Equity', '300070 CH Equity', '300024 CH Equity', '002303 CH Equity', '601106 CH Equity', '000778 CH Equity', '000786 CH Equity', '000815 CH Equity', '002468 CH Equity', '002640 CH Equity', '600179 CH Equity', '002145 CH Equity', '600829 CH Equity', '601618 CH Equity', '002079 CH Equity', '300118 CH Equity', '300026 CH Equity', '300294 CH Equity', '300278 CH Equity', '002073 CH Equity', '300308 CH Equity', '002727 CH Equity', '601012 CH Equity', '002714 CH Equity', '603185 CH Equity', '601016 CH Equity', '002670 CH Equity', '603000 CH Equity', '300369 CH Equity', '603077 CH Equity', '002673 CH Equity', '002717 CH Equity', '603328 CH Equity', '002709 CH Equity', '601608 CH Equity', '002683 CH Equity', '002690 CH Equity', '603288 CH Equity', '300315 CH Equity', '300383 CH Equity', '603766 CH Equity', '002698 CH Equity', '002745 CH Equity', '601225 CH Equity', '002701 CH Equity', '002678 CH Equity', '300316 CH Equity', '002815 CH Equity', '300347 CH Equity', '603777 CH Equity', '603806 CH Equity', '601969 CH Equity', '600917 CH Equity', '300357 CH Equity', '300373 CH Equity', '300363 CH Equity', '002705 CH Equity', '002736 CH Equity', '300729 CH Equity', '000166 CH Equity', '600919 CH Equity', '601825 CH Equity', '601611 CH Equity', '600989 CH Equity', '300999 CH Equity', '600926 CH Equity', '600918 CH Equity', '300601 CH Equity', '300498 CH Equity', '002916 CH Equity', '300413 CH Equity', '300759 CH Equity', '300432 CH Equity', '688099 CH Equity', '603737 CH Equity', '002938 CH Equity', '002821 CH Equity', '600968 CH Equity', '300415 CH Equity', '603379 CH Equity', '600903 CH Equity', '300741 CH Equity', '002786 CH Equity', '603355 CH Equity', '002920 CH Equity', '300760 CH Equity', '603365 CH Equity', '603818 CH Equity', '688777 CH Equity', '603589 CH Equity', '601163 CH Equity', '603233 CH Equity', '605358 CH Equity', '603225 CH Equity', '603927 CH Equity', '603596 CH Equity', '603638 CH Equity', '603893 CH Equity', '601568 CH Equity', '603707 CH Equity', '601966 CH Equity', '603708 CH Equity', '002791 CH Equity', '603883 CH Equity', '603369 CH Equity', '601615 CH Equity', '603198 CH Equity', '603899 CH Equity', '300450 CH Equity', '603885 CH Equity', '603228 CH Equity', '300482 CH Equity', '300850 CH Equity', '002850 CH Equity', '300529 CH Equity', '600927 CH Equity', '603456 CH Equity', '601236 CH Equity', '300376 CH Equity', '300390 CH Equity', '601128 CH Equity', '601212 CH Equity', '603833 CH Equity', '300408 CH Equity', '002747 CH Equity', '300628 CH Equity', '603267 CH Equity', '603290 CH Equity', '603338 CH Equity', '300618 CH Equity', '603712 CH Equity', '603799 CH Equity', '002841 CH Equity', '002939 CH Equity', '603786 CH Equity', '601021 CH Equity', '600025 CH Equity', '603013 CH Equity', '603392 CH Equity', '002738 CH Equity', '600901 CH Equity', '603026 CH Equity', '603816 CH Equity', '002756 CH Equity', '002773 CH Equity', '000333 CH Equity', '600023 CH Equity', '600909 CH Equity', '002739 CH Equity', '601211 CH Equity', '601198 CH Equity', '600958 CH Equity', '601689 CH Equity', '603606 CH Equity', '300463 CH Equity', '603866 CH Equity', '600959 CH Equity', '300511 CH Equity', '300418 CH Equity', '601985 CH Equity', '603868 CH Equity', '603515 CH Equity', '603569 CH Equity', '603986 CH Equity', '300496 CH Equity', '603160 CH Equity', '300433 CH Equity', '603317 CH Equity', '002797 CH Equity', '603018 CH Equity', '603939 CH Equity', '300474 CH Equity', '601127 CH Equity', '603444 CH Equity', '603568 CH Equity', '002812 CH Equity', '603658 CH Equity', '600977 CH Equity', '603019 CH Equity', '603345 CH Equity', '603858 CH Equity', '300558 CH Equity', '002839 CH Equity', '300458 CH Equity', '601838 CH Equity', '601997 CH Equity', '002831 CH Equity', '603517 CH Equity', '603218 CH Equity', '300682 CH Equity', '002847 CH Equity', '300568 CH Equity', '603127 CH Equity', '603501 CH Equity', '002926 CH Equity', '601878 CH Equity', '300608 CH Equity', '300595 CH Equity', '603056 CH Equity', '688208 CH Equity', '300699 CH Equity', '603587 CH Equity', '601108 CH Equity', '300661 CH Equity', '601155 CH Equity', '601019 CH Equity', '300676 CH Equity', '001979 CH Equity', '603260 CH Equity', '601619 CH Equity', '601228 CH Equity', '603882 CH Equity', '300888 CH Equity', '300832 CH Equity', '300677 CH Equity', '300672 CH Equity', '002901 CH Equity', '603605 CH Equity', '300687 CH Equity', '603659 CH Equity', '300769 CH Equity', '002945 CH Equity', '002925 CH Equity', '300726 CH Equity', '300827 CH Equity', '002958 CH Equity', '601860 CH Equity', '603156 CH Equity', '601577 CH Equity', '600928 CH Equity', '603486 CH Equity', '300773 CH Equity', '300604 CH Equity', '601990 CH Equity', '300725 CH Equity', '002966 CH Equity', '601162 CH Equity', '601200 CH Equity', '300783 CH Equity', '300724 CH Equity', '688111 CH Equity', '688029 CH Equity', '300751 CH Equity', '603650 CH Equity', '300896 CH Equity', '688202 CH Equity', '603259 CH Equity', '300748 CH Equity', '300454 CH Equity', '002946 CH Equity', '603613 CH Equity', '300763 CH Equity', '300750 CH Equity', '300770 CH Equity', '001965 CH Equity', '601698 CH Equity', '603087 CH Equity', '601138 CH Equity', '300782 CH Equity', '688301 CH Equity', '603719 CH Equity', '300869 CH Equity', '688006 CH Equity', '603195 CH Equity', '300861 CH Equity', '002975 CH Equity', '601696 CH Equity', '601778 CH Equity', '688005 CH Equity', '688002 CH Equity', '688116 CH Equity', '688012 CH Equity', '688036 CH Equity', '688008 CH Equity', '688068 CH Equity', '688169 CH Equity', '688363 CH Equity', '688188 CH Equity', '688122 CH Equity', '688126 CH Equity', '300866 CH Equity', '688599 CH Equity', '003022 CH Equity', '688396 CH Equity', '688516 CH Equity', '605117 CH Equity', '688521 CH Equity', '601816 CH Equity', '688065 CH Equity', '688390 CH Equity', '688289 CH Equity', '688256 CH Equity', '003035 CH Equity', '600905 CH Equity', '688536 CH Equity', '688608 CH Equity', '605499 CH Equity', '300919 CH Equity', '688561 CH Equity', '688063 CH Equity', '300979 CH Equity', '300957 CH Equity', '002138 CH Equity', '002470 CH Equity', '600052 CH Equity', '002603 CH Equity', '900932 CH Equity', '201872 CH Equity', '600371 CH Equity', '600655 CH Equity', '600673 CH Equity', '600664 CH Equity', '600660 CH Equity', '600675 CH Equity', '600674 CH Equity', '600699 CH Equity', '000001 CH Equity', '000100 CH Equity', '600881 CH Equity', '000826 CH Equity', '900909 CH Equity', '600196 CH Equity', '000830 CH Equity', '000652 CH Equity', '600583 CH Equity', '000950 CH Equity', '000655 CH Equity', '000301 CH Equity', '601567 CH Equity', '600685 CH Equity', '600808 CH Equity', '000656 CH Equity', '600019 CH Equity', '600777 CH Equity', '000547 CH Equity', '200541 CH Equity', '900903 CH Equity', '000501 CH Equity', '000425 CH Equity', '000543 CH Equity', '000031 CH Equity', '600741 CH Equity', '600433 CH Equity', '600737 CH Equity', '600740 CH Equity', '000059 CH Equity', '000035 CH Equity', '900928 CH Equity', '600839 CH Equity', '600635 CH Equity', '600836 CH Equity', '600637 CH Equity', '000555 CH Equity', '600629 CH Equity', '900934 CH Equity', '600633 CH Equity', '600690 CH Equity', '900920 CH Equity', '000591 CH Equity', '600815 CH Equity', '002038 CH Equity', '600654 CH Equity', '600820 CH Equity', '002595 CH Equity', '000519 CH Equity', '900921 CH Equity', '600643 CH Equity', '900925 CH Equity', '600621 CH Equity', '600628 CH Equity', '600693 CH Equity', '000819 CH Equity', '600645 CH Equity', '600644 CH Equity', '000513 CH Equity', '600642 CH Equity', '600691 CH Equity', '600078 CH Equity', '000729 CH Equity', '600653 CH Equity', '000797 CH Equity', '002195 CH Equity', '600864 CH Equity', '000807 CH Equity', '600886 CH Equity', '002508 CH Equity', '000629 CH Equity', '600876 CH Equity', '000592 CH Equity', '000825 CH Equity', '600198 CH Equity', '002466 CH Equity', '600718 CH Equity', '000970 CH Equity', '600708 CH Equity', '300222 CH Equity', '000060 CH Equity', '600176 CH Equity', '001696 CH Equity', '000401 CH Equity', '000630 CH Equity', '002176 CH Equity', '600739 CH Equity', '600780 CH Equity', '600773 CH Equity', '600770 CH Equity', '200725 CH Equity', '000408 CH Equity', '000881 CH Equity', '600518 CH Equity', '002080 CH Equity', '600067 CH Equity', '002292 CH Equity', '000717 CH Equity', '000768 CH Equity', '000898 CH Equity', '002503 CH Equity', '200726 CH Equity', '900947 CH Equity', '600072 CH Equity', '900952 CH Equity', '600158 CH Equity', '000739 CH Equity', '600108 CH Equity', '000703 CH Equity', '000792 CH Equity', '002405 CH Equity', '600009 CH Equity', '000157 CH Equity', '600403 CH Equity', '002409 CH Equity', '600150 CH Equity', '600180 CH Equity', '600435 CH Equity', '600439 CH Equity', '000861 CH Equity', '601158 CH Equity', '000878 CH Equity', '600163 CH Equity', '600165 CH Equity', '002078 CH Equity', '600804 CH Equity', '000009 CH Equity', '600805 CH Equity', '000568 CH Equity', '000006 CH Equity', '600807 CH Equity', '000525 CH Equity', '600606 CH Equity', '000885 CH Equity', '600201 CH Equity', '000552 CH Equity', '600684 CH Equity', '600620 CH Equity', '600993 CH Equity', '600616 CH Equity', '600008 CH Equity', '000540 CH Equity', '000852 CH Equity', '600405 CH Equity', '601872 CH Equity', '002094 CH Equity', '000598 CH Equity', '600732 CH Equity', '600888 CH Equity', '000672 CH Equity', '200413 CH Equity', '000663 CH Equity', '900936 CH Equity', '600879 CH Equity', '000607 CH Equity', '600795 CH Equity', '600750 CH Equity', '600779 CH Equity', '000800 CH Equity', '600893 CH Equity', '600757 CH Equity', '002555 CH Equity', '600755 CH Equity', '600882 CH Equity', '600798 CH Equity', '600729 CH Equity', '600749 CH Equity', '000876 CH Equity', '002250 CH Equity', '600705 CH Equity', '600703 CH Equity', '000676 CH Equity', '000159 CH Equity', '000158 CH Equity', '000402 CH Equity', '600126 CH Equity', '000829 CH Equity', '600378 CH Equity', '600138 CH Equity', '600051 CH Equity', '600775 CH Equity', '600792 CH Equity', '600704 CH Equity', '900940 CH Equity', '600141 CH Equity', '600053 CH Equity', '000718 CH Equity', '600120 CH Equity', '600580 CH Equity', '600246 CH Equity', '000400 CH Equity', '601699 CH Equity', '600797 CH Equity', '000423 CH Equity', '300144 CH Equity', '000612 CH Equity', '600707 CH Equity', '002608 CH Equity', '600398 CH Equity', '600021 CH Equity', '600562 CH Equity', '600284 CH Equity', '600468 CH Equity', '600415 CH Equity', '600303 CH Equity', '601766 CH Equity', '600331 CH Equity', '600510 CH Equity', '600420 CH Equity', '601888 CH Equity', '600100 CH Equity', '600446 CH Equity', '600482 CH Equity', '000981 CH Equity', '900948 CH Equity', '002597 CH Equity', '002048 CH Equity', '600089 CH Equity', '002102 CH Equity', '600460 CH Equity', '000090 CH Equity', '000998 CH Equity', '600197 CH Equity', '600356 CH Equity', '600218 CH Equity', '000021 CH Equity', '600597 CH Equity', '601688 CH Equity', '600017 CH Equity', '600273 CH Equity', '600409 CH Equity', '600391 CH Equity', '002004 CH Equity', '600588 CH Equity', '600486 CH Equity', '600787 CH Equity', '601100 CH Equity', '000839 CH Equity', '600498 CH Equity', '002202 CH Equity', '600556 CH Equity', '600962 CH Equity', '600170 CH Equity', '002178 CH Equity', '002001 CH Equity', '002082 CH Equity', '600323 CH Equity', '002511 CH Equity', '600521 CH Equity', '600007 CH Equity', '600396 CH Equity', '002121 CH Equity', '002215 CH Equity', '002294 CH Equity', '600322 CH Equity', '000812 CH Equity', '600566 CH Equity', '000681 CH Equity', '000733 CH Equity', '002531 CH Equity', '600469 CH Equity', '600874 CH Equity', '601007 CH Equity', '600875 CH Equity', '600123 CH Equity', '002212 CH Equity', '600884 CH Equity', '600300 CH Equity', '002240 CH Equity', '000967 CH Equity', '002352 CH Equity', '600277 CH Equity', '000930 CH Equity', '002241 CH Equity', '600233 CH Equity', '600036 CH Equity', '000968 CH Equity', '000977 CH Equity', '000603 CH Equity', '600033 CH Equity', '000635 CH Equity', '600117 CH Equity', '200055 CH Equity', '600256 CH Equity', '002122 CH Equity', '600221 CH Equity', '600309 CH Equity', '002242 CH Equity', '600500 CH Equity', '601901 CH Equity', '600269 CH Equity', '002252 CH Equity', '601229 CH Equity', '600037 CH Equity', '601668 CH Equity', '600873 CH Equity', '002681 CH Equity', '600550 CH Equity', '600765 CH Equity', '600337 CH Equity', '000975 CH Equity', '600310 CH Equity', '600299 CH Equity', '600487 CH Equity', '002074 CH Equity', '600153 CH Equity', '600386 CH Equity', '600316 CH Equity', '000620 CH Equity', '002028 CH Equity', '600594 CH Equity', '002497 CH Equity', '000960 CH Equity', '002648 CH Equity', '000937 CH Equity', '200771 CH Equity', '000831 CH Equity', '000900 CH Equity', '002475 CH Equity', '600333 CH Equity', '000993 CH Equity', '600312 CH Equity', '600338 CH Equity', '300085 CH Equity', '002387 CH Equity', '002440 CH Equity', '600483 CH Equity', '002002 CH Equity', '600167 CH Equity', '600973 CH Equity', '002601 CH Equity', '600536 CH Equity', '600259 CH Equity', '002093 CH Equity', '600200 CH Equity', '600143 CH Equity', '000917 CH Equity', '600983 CH Equity', '600867 CH Equity', '002005 CH Equity', '600982 CH Equity', '000938 CH Equity', '300223 CH Equity', '002098 CH Equity', '300274 CH Equity', '600508 CH Equity', '002064 CH Equity', '600596 CH Equity', '200025 CH Equity', '600243 CH Equity', '600018 CH Equity', '600499 CH Equity', '000988 CH Equity', '600373 CH Equity', '300159 CH Equity', '600022 CH Equity', '601166 CH Equity', '002293 CH Equity', '002021 CH Equity', '601989 CH Equity', '000690 CH Equity', '600020 CH Equity', '600423 CH Equity', '002419 CH Equity', '000498 CH Equity', '600290 CH Equity', '000738 CH Equity', '600079 CH Equity', '002304 CH Equity', '002589 CH Equity', '600592 CH Equity', '600997 CH Equity', '600549 CH Equity', '600039 CH Equity', '002390 CH Equity', '000046 CH Equity', '000559 CH Equity', '002092 CH Equity',

In [806]:
# Assign row as column headers
header_row = fin_data.iloc[2]
fin_data = pd.DataFrame(fin_data.values[3:], columns=header_row)
fin_data = fin_data.set_index(["Dates"])
fin_data.head()

2,PX_LAST,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,CF_FREE_CASH_FLOW,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,VOLATILITY_360D,...,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,CF_FREE_CASH_FLOW,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,VOLATILITY_360D,BETA_RAW_OVERRIDABLE
Dates,,,,,,,,,,,,,,,,,,,,,
2023-01-31,22.3,33130.4997,2.5659,0.1741,77.3828,35.5719,12.4809,8.8031,43.782,40.754,...,5847.9545,4.0972,0.0487,112.6397,64.4757,10.5395,1.9394,40.799,41.581,1.2659
2022-12-30,22.63,33130.4997,2.5659,0.1741,77.3828,36.0983,12.4809,8.8031,45.394,41.121,...,5847.9545,4.0972,0.0487,112.6397,60.9747,10.5395,1.9394,43.11,41.779,1.267
2022-11-30,20.46,33130.4997,2.5659,0.1741,77.3828,32.6368,12.4809,8.8031,45.309,40.336,...,5847.9545,4.0972,0.0487,112.6397,65.9344,10.5395,1.9394,45.135,42.1,1.2151
2022-10-31,17.73,33130.4997,2.5659,0.1741,77.3828,28.2821,12.4809,8.8031,43.637,39.217,...,5847.9545,4.0972,0.0487,112.6397,60.683,10.5395,1.9394,44.954,42.679,1.2737
2022-09-30,18.16,33130.4997,2.5659,0.1741,77.3828,28.968,12.4809,8.8031,41.724,37.894,...,5847.9545,4.0972,0.0487,112.6397,65.0592,10.5395,1.9394,44.338,42.916,1.2673

In [807]:
len(company_list)

1303

In [808]:
i = 0 
j = 0
frames = []
table_columns_len = len(fin_data.columns)
while table_columns_len > 0:
    i += 1
    globals()["fin_data_%s"%i] = fin_data.iloc[:, (0+j):(11+j)]
    globals()["fin_data_%s"%i].insert(0,"Tkr & Exch", company_list[i-1])
    j+=11
    table_columns_len -= 11
    frames.append(globals()["fin_data_%s"%i])
print(i)
fin_data_1.head()

1303

2,Tkr & Exch,PX_LAST,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,CF_FREE_CASH_FLOW,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,VOLATILITY_360D,BETA_RAW_OVERRIDABLE
Dates,,,,,,,,,,,,
2023-01-31,002007 CH Equity,22.3,33130.4997,2.5659,0.1741,77.3828,35.5719,12.4809,8.8031,43.782,40.754,1.2221
2022-12-30,002007 CH Equity,22.63,33130.4997,2.5659,0.1741,77.3828,36.0983,12.4809,8.8031,45.394,41.121,1.3581
2022-11-30,002007 CH Equity,20.46,33130.4997,2.5659,0.1741,77.3828,32.6368,12.4809,8.8031,45.309,40.336,1.3668
2022-10-31,002007 CH Equity,17.73,33130.4997,2.5659,0.1741,77.3828,28.2821,12.4809,8.8031,43.637,39.217,1.2791
2022-09-30,002007 CH Equity,18.16,33130.4997,2.5659,0.1741,77.3828,28.968,12.4809,8.8031,41.724,37.894,1.1797

Append the dataframe

In [809]:
fin_data_full = pd.concat(frames)
fin_data_full.head()

2,Tkr & Exch,PX_LAST,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,CF_FREE_CASH_FLOW,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,VOLATILITY_360D,BETA_RAW_OVERRIDABLE
Dates,,,,,,,,,,,,
2023-01-31,002007 CH Equity,22.3,33130.4997,2.5659,0.1741,77.3828,35.5719,12.4809,8.8031,43.782,40.754,1.2221
2022-12-30,002007 CH Equity,22.63,33130.4997,2.5659,0.1741,77.3828,36.0983,12.4809,8.8031,45.394,41.121,1.3581
2022-11-30,002007 CH Equity,20.46,33130.4997,2.5659,0.1741,77.3828,32.6368,12.4809,8.8031,45.309,40.336,1.3668
2022-10-31,002007 CH Equity,17.73,33130.4997,2.5659,0.1741,77.3828,28.2821,12.4809,8.8031,43.637,39.217,1.2791
2022-09-30,002007 CH Equity,18.16,33130.4997,2.5659,0.1741,77.3828,28.968,12.4809,8.8031,41.724,37.894,1.1797

In [810]:
fin_data_full = fin_data_full.reset_index()
fin_data_full.head()

2,Dates,Tkr & Exch,PX_LAST,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,CF_FREE_CASH_FLOW,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,VOLATILITY_360D,BETA_RAW_OVERRIDABLE
0,2023-01-31,002007 CH Equity,22.3,33130.4997,2.5659,0.1741,77.3828,35.5719,12.4809,8.8031,43.782,40.754,1.2221
1,2022-12-30,002007 CH Equity,22.63,33130.4997,2.5659,0.1741,77.3828,36.0983,12.4809,8.8031,45.394,41.121,1.3581
2,2022-11-30,002007 CH Equity,20.46,33130.4997,2.5659,0.1741,77.3828,32.6368,12.4809,8.8031,45.309,40.336,1.3668
3,2022-10-31,002007 CH Equity,17.73,33130.4997,2.5659,0.1741,77.3828,28.2821,12.4809,8.8031,43.637,39.217,1.2791
4,2022-09-30,002007 CH Equity,18.16,33130.4997,2.5659,0.1741,77.3828,28.968,12.4809,8.8031,41.724,37.894,1.1797

Select the yearly data

In [811]:
fin_data_full = fin_data_full.loc[(fin_data_full['Dates'].dt.month==12) | ((fin_data_full['Dates'].dt.year == 2023) & (fin_data_full['Dates'].dt.month==1))]
fin_data_full.insert(0, "Year", fin_data_full['Dates'].dt.year)
fin_data_full.head()

2,Year,Dates,Tkr & Exch,PX_LAST,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,CF_FREE_CASH_FLOW,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,VOLATILITY_360D,BETA_RAW_OVERRIDABLE
0,2023,2023-01-31,002007 CH Equity,22.3,33130.4997,2.5659,0.1741,77.3828,35.5719,12.4809,8.8031,43.782,40.754,1.2221
1,2022,2022-12-30,002007 CH Equity,22.63,33130.4997,2.5659,0.1741,77.3828,36.0983,12.4809,8.8031,45.394,41.121,1.3581
13,2021,2021-12-31,002007 CH Equity,29.14,53036.2403,2.4379,0.133,230.8581,40.7466,16.4191,12.0735,33.856,45.939,0.9305
25,2020,2020-12-31,002007 CH Equity,42.24,76652.9935,2.5888,0.3566,620.4098,50.2723,22.927,18.308,53.488,46.606,0.8532
37,2019,2019-12-31,002007 CH Equity,27.038,49317.5246,2.0286,0.1752,536.9706,38.4313,21.2662,18.2357,32.948,42.141,0.9144

## Read the ESG data

### Case CN

In [812]:
esgdata_sheet = pd.read_excel(bloomberg, sheet_name="ESG", header=1)

esg_data = pd.DataFrame(esgdata_sheet)
esg_data.head()

,LCL,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Ticker,Name,ESG Disc Score:Y,Gov Disc Sc:Y,Soc Disc Sc:Y,Env Disc Sc:Y,Year
1,None (1303 securities),NaN,NaN,NaN,NaN,NaN,NaN
2,002138 CH Equity,SHENZHEN SUNLORD ELECTRONI-A,33.839653,75.195663,11.547763,14.61794,2022
3,002470 CH Equity,KINGENTA ECOLOGICAL ENGINE-A,37.33025,75.195663,13.422007,23.225613,2022
4,600052 CH Equity,ZHEJIANG DONGWANG TIMES TE-A,33.075142,77.69416,7.829504,13.530655,2022

In [813]:
header_row_esg = esg_data.iloc[0]
esg_data = pd.DataFrame(esg_data.values[2:], columns=header_row_esg)
esg_data = esg_data.set_index(["Year"])
esg_data = esg_data.drop(["Name"], axis=1)
esg_data = esg_data.rename({"Ticker": "Tkr & Exch", 
                            "ESG Disc Score:Y": "esg", 
                            "Gov Disc Sc:Y": "g", 
                            "Soc Disc Sc:Y": "s",
                            "Env Disc Sc:Y": "e"}, axis=1)
esg_data = esg_data.reset_index()
esg_data.head()

0  Year        Tkr & Exch        esg          g          s          e
0  2022  002138 CH Equity  33.839653  75.195663  11.547763   14.61794
1  2022  002470 CH Equity   37.33025  75.195663  13.422007  23.225613
2  2022  600052 CH Equity  33.075142   77.69416   7.829504  13.530655
3  2022  002603 CH Equity  37.108944  72.065018  15.598549  23.527636
4  2022  900932 CH Equity  37.370487  75.195663  19.044741  17.728783

### Case AU, HK, MY, SG

In [814]:
# esgdata_sheet = pd.read_excel(bloomberg, sheet_name="ESG")

# esg_data = pd.DataFrame(esgdata_sheet)
# esg_data.head()

In [815]:
# columns = esg_data.columns
# columns_year = ""
# for column in columns:
#     if ('year' in column.lower()):
#         columns_year = column.title()
#         esg_data =  esg_data.rename({column:columns_year}, axis=1)
#         esg_data = esg_data.set_index(columns_year)
# esg_data = esg_data.drop(["Name"], axis=1)
# esg_data = esg_data.rename( {"Ticker": "Tkr & Exch", 
#                             "ESG Disc Score:Y": "esg", 
#                             "Gov Disc Sc:Y": "g", 
#                             "Soc Disc Sc:Y": "s",
#                             "Env Disc Sc:Y": "e"}, axis=1)
# esg_data = esg_data.reset_index()
# esg_data.head()

### All

In [816]:
fin_esg_data_full = pd.merge(fin_data_full, esg_data, on=['Year', 'Tkr & Exch'], how='left')
fin_esg_data_full.head()

,Year,Dates,Tkr & Exch,PX_LAST,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,CF_FREE_CASH_FLOW,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,VOLATILITY_360D,BETA_RAW_OVERRIDABLE,esg,g,s,e
0,2023,2023-01-31,002007 CH Equity,22.3,33130.4997,2.5659,0.1741,77.3828,35.5719,12.4809,8.8031,43.782,40.754,1.2221,NaN,NaN,NaN,NaN
1,2022,2022-12-30,002007 CH Equity,22.63,33130.4997,2.5659,0.1741,77.3828,36.0983,12.4809,8.8031,45.394,41.121,1.3581,31.978674,70.680313,9.643289,15.463606
2,2021,2021-12-31,002007 CH Equity,29.14,53036.2403,2.4379,0.133,230.8581,40.7466,16.4191,12.0735,33.856,45.939,0.9305,31.757368,70.680313,9.643289,14.799154
3,2020,2020-12-31,002007 CH Equity,42.24,76652.9935,2.5888,0.3566,620.4098,50.2723,22.927,18.308,53.488,46.606,0.8532,31.56624,70.108368,9.643289,14.799154
4,2019,2019-12-31,002007 CH Equity,27.038,49317.5246,2.0286,0.1752,536.9706,38.4313,21.2662,18.2357,32.948,42.141,0.9144,31.56624,70.108368,9.643289,14.799154

### Add the GICS sector

In [817]:
GICS = pd.ExcelFile("..\Sray\original dirty data\GICS sector by country (robusness check).xlsx")

'''CH'''
GICS_SECTOR = pd.read_excel(GICS, sheet_name="CH")

'''AU'''
# GICS_SECTOR = pd.read_excel(GICS, sheet_name="AU")

'''HK'''
# GICS_SECTOR = pd.read_excel(GICS, sheet_name="HK")

'''MY'''
# GICS_SECTOR = pd.read_excel(GICS, sheet_name="MK")

'''SG'''
# GICS_SECTOR = pd.read_excel(GICS, sheet_name="SG")

GICS_SECTOR_pd = pd.DataFrame(GICS_SECTOR)
GICS_SECTOR_pd.head()

             Ticker                          Name             GICS Sector
0  600808 CH Equity       MAANSHAN IRON & STEEL-A               Materials
1  000513 CH Equity  LIVZON PHARMACEUTICAL GROU-A             Health Care
2  601231 CH Equity  UNIVERSAL SCIENTIFIC INDUS-A  Information Technology
3  002821 CH Equity  ASYMCHEM LABORATORIES TIAN-A             Health Care
4  300274 CH Equity  SUNGROW POWER SUPPLY CO LT-A             Industrials

In [818]:
sec_no = pd.read_excel(GICS, sheet_name="Sector No")
sec_no_pd = pd.DataFrame(sec_no)

sec_no_pd = sec_no_pd.rename({'sector' : 'GICS Sector', 'sec_no': 'sec_no'.capitalize()}, axis=1)
sec_no_pd.head()

              GICS Sector  Sec_no
0                  Energy       1
1               Materials       2
2             Industrials       3
3  Consumer Discretionary       4
4        Consumer Staples       5

In [819]:
GICS_SECTOR_pd = pd.merge(GICS_SECTOR_pd, sec_no_pd, on=['GICS Sector'])
GICS_SECTOR_pd = GICS_SECTOR_pd.rename({'Ticker': 'Tkr & Exch'}, axis=1)
GICS_SECTOR_pd = GICS_SECTOR_pd.drop(['GICS Sector'], axis=1)
GICS_SECTOR_pd = GICS_SECTOR_pd.sort_values(['Tkr & Exch'])

GICS_SECTOR_pd.head()

           Tkr & Exch                         Name  Sec_no
841  000001 CH Equity        PING AN BANK CO LTD-A       7
944  000006 CH Equity   SHENZHEN ZHENYE GROUP CO-A      11
674  000008 CH Equity  CHINA HIGH-SPEED RAILWAY -A       3
660  000009 CH Equity          CHINA BAOAN GROUP-A       3
419  000021 CH Equity  SHENZHEN KAIFA TECHNOLOGY-A       8

In [820]:
firm_no_pd = pd.DataFrame(fin_esg_data_full['Tkr & Exch'])
firm_no_pd = firm_no_pd.drop_duplicates()
firm_no_pd = firm_no_pd.reset_index(drop=True)
firm_no_pd.index += 1
firm_no_pd.index.name = 'firm no'
firm_no_pd = firm_no_pd.reset_index()
firm_no_pd.tail()

      firm no        Tkr & Exch
1298     1299  600125 CH Equity
1299     1300  000810 CH Equity
1300     1301  601139 CH Equity
1301     1302  002541 CH Equity
1302     1303  600609 CH Equity

In [821]:
fin_esg_gics_data_full = pd.merge(fin_esg_data_full, firm_no_pd, on=['Tkr & Exch'], how='left')
fin_esg_gics_data_full = pd.merge(fin_esg_gics_data_full, GICS_SECTOR_pd, on=['Tkr & Exch'], how='left')
Sec_No_Column = fin_esg_gics_data_full.pop('Sec_no')
Firm_No_Column = fin_esg_gics_data_full.pop('firm no')
Name_No_Column = fin_esg_gics_data_full.pop('Name')
fin_esg_gics_data_full.insert(0, 'firm no', Firm_No_Column)
fin_esg_gics_data_full.insert(4, 'Name', Name_No_Column)
fin_esg_gics_data_full.insert(5, 'Sec_no', Sec_No_Column)
fin_esg_gics_data_full = fin_esg_gics_data_full.sort_values(['firm no', 'Year'])
fin_esg_gics_data_full.tail()

,firm no,Year,Dates,Tkr & Exch,Name,Sec_no,PX_LAST,HISTORICAL_MARKET_CAP,TRAIL_12M_SALES_PER_SH,IS_EPS,...,PE_RATIO,RETURN_COM_EQY,RETURN_ON_ASSET,VOLATILITY_180D,VOLATILITY_360D,BETA_RAW_OVERRIDABLE,esg,g,s,e
10420,1303,2019,2019-12-31,600609 CH Equity,SHENYANG JINBEI AUTOMOTIVE-A,4.0,3.96,4326.9618,5.1252,0.006,...,71.7807,15.6172,1.0353,41.06,41.45,1.2084,28.598734,75.195663,3.657799,6.765328
10419,1303,2020,2020-12-31,600609 CH Equity,SHENYANG JINBEI AUTOMOTIVE-A,4.0,5.73,7513.1792,4.4181,-0.3929,...,107.6406,-92.4115,-8.3233,64.381,53.847,1.2542,26.345438,75.195663,3.657799,0
10418,1303,2021,2021-12-31,600609 CH Equity,SHENYANG JINBEI AUTOMOTIVE-A,4.0,5.33,6988.699,3.9588,-0.0323,...,35.7661,28.9999,4.1794,41.361,50.524,0.7484,26.345438,75.195663,3.657799,0
10417,1303,2022,2022-12-30,600609 CH Equity,SHENYANG JINBEI AUTOMOTIVE-A,4.0,4.18,5847.9545,4.0972,0.0487,...,60.9747,10.5395,1.9394,43.11,41.779,1.267,26.687456,75.195663,4.685611,0
10416,1303,2023,2023-01-31,600609 CH Equity,SHENYANG JINBEI AUTOMOTIVE-A,4.0,4.42,5847.9545,4.0972,0.0487,...,64.4757,10.5395,1.9394,40.799,41.581,1.2659,NaN,NaN,NaN,NaN

In [822]:
fin_esg_gics_data_full.to_excel(r"..\Sray\fin concate esg\CN_bloom_fin_esg.xlsx", sheet_name="fin_esg", index=False)
# fin_esg_gics_data_full.to_excel(r"..\Sray\fin concate esg\AU_bloom_fin_esg.xlsx", sheet_name="fin_esg", index=False)
# fin_esg_gics_data_full.to_excel(r"..\Sray\fin concate esg\HK_bloom_fin_esg.xlsx", sheet_name="fin_esg", index=False)
# fin_esg_gics_data_full.to_excel(r"..\Sray\fin concate esg\MY_bloom_fin_esg.xlsx", sheet_name="fin_esg", index=False)
# fin_esg_gics_data_full.to_excel(r"..\Sray\fin concate esg\SG_bloom_fin_esg.xlsx", sheet_name="fin_esg", index=False)